### ISSUE TITLE
Optional regex for sonarr removed with sync

### ISSUE THREAD

**Issue by pvries86** [rcdailey/trash-updater#19]
Is there a way to sync the optional preferred preferences for sonarr? I have now manually added the regex for Optional Ignore DoVi for WEBDL, but this gets removed from sonarr when I run the sync.
Maybe this can be added like it is done for radarr?

**Comment by rcdailey** [comment]
At the moment, there is no way to sync optional preferred. It's on my list but it's complicated to implement. Right now the best workaround is to create a new release profile using the same tag you use for TV. Add your optional preferred to that list, and it won't get overwritten by Trash Updater. Since it shares the same tag, it will supplement your series searches all the same.

Hopefully this works for you in the meantime.

**Comment by pvries86** [comment]
Thanks, that workaround is easily usable and allows me to continue to use your tool!
