### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by zhdenny** [rcdailey/trash-updater#2]
Just playing with this and running the preview and help menus. There is confusion between "non-anime" and "web-dl" throughout the help and preview outputs. 

**For example, these specific commands work:**
```
python3 trash.py quality sonarr:non-anime --preview
python3 trash.py profile sonarr:web-dl --preview
```

**while these specific commands spit out error:**
```
python3 trash.py profile sonarr:non-anime --preview
python3 trash.py quality sonarr:web-dl --preview
```

Outside of that, both sonarr and sonarr anime profile runs worked excellent for me. I checked results of each one. I didn't wanna run quality or any radarr stuff so I didn't check them.

This is excellent and I hope to see great collaboration between you and TRaSH project so this stays in-line!

**Comment by rcdailey** [comment]
First, thanks for the compliments. I agree that the command line is very confusing right now. I've had a hard time figuring out how I want to structure the subcommands. I've come to the conclusion that it's sort of "backwards". It should really be something along the lines of `trash.py sonarr non-anime`, basically with the specific service as the subcommand instead of the type of guide.

I am currently working on a complete rewrite of the scripts using C# .NET Core. The script has gotten really big and I dislike Python for large programs. It will take me a while, but please look forward to the new rewritten version!

**Comment by zhdenny** [comment]
woah, cool man!
Although, I already basically set your script up to auto pull latest and run trash updates daily ROFL. I just wanted a set it and forget it solution. I'll need to pay attention to when you release a big update. Might break the commands already in place. Nnot a bad thing by the way...just something I need to pay attention to

Thank you man! Cheers
