### ISSUE TITLE
[CLI] Help message not showing error message when using non-existant subcommand

### ISSUE THREAD

**Issue by skayo** [rcdailey/trash-updater#46]
When running `trash nonexistant` it prints the following:
```
Unexpected parameter(s):
<nonexistant>

trash v1.8.2

USAGE
  trash [options]
  trash [command] [...]

OPTIONS
  -h|--help         Shows help text.
  --version         Shows version information.

COMMANDS
  create-config     Create a starter YAML configuration file
  radarr            Perform operations on a Radarr instance
  sonarr            Perform operations on a Sonarr instance

You can run `trash [command] --help` to show help on a specific command.
```

But when running `trash nonexistant --help`, it only prints this:
```
trash v1.8.2

USAGE
  trash [options]
  trash [command] [...]

OPTIONS
  -h|--help         Shows help text.
  --version         Shows version information.

COMMANDS
  create-config     Create a starter YAML configuration file
  radarr            Perform operations on a Radarr instance
  sonarr            Perform operations on a Sonarr instance

You can run `trash [command] --help` to show help on a specific command.
```

I think when trying to get help for a subcommand that doesn't exist it should also show some kind of error.  
Just a minor "issue", really. Noticed it while working on the docker image :)

**Comment by rcdailey** [comment]
I took a look at the CliFx code base and this is working as intended. Any time the `--help` option is specified, no matter what the subcommand is, it prints the help text and exits. This happens before any subcommand processing occurs.

Furthermore, it is also by design that if you specify an unexpected parameter, it prints the help text following the error message.
